/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.UsuarioDAO;
import controller.ReservaDAO;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Date;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Usuario;
import model.Reserva;

/**
 *
 * @author louis
 */
public class FormularioUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form FormularioUsuarios
     */
    private Usuario usuario;
    static private String Mode = "";
    static private long id = 0;
    private ListadoUsuarios parent;
    UsuarioDAO dao = new UsuarioDAO();
    
    public FormularioUsuarios(ListadoUsuarios parent, boolean modal, String Mode, long id) {
        super(parent, modal);    
        this.parent = parent;
        initComponents();
        
        this.Mode = Mode;
        this.id = id;
        
        usuario = new Usuario();
        
        List<String> roles = new ArrayList<>();
        roles.add("recepcionista");
        roles.add("admin");
        
        DefaultComboBoxModel<String> modelRoles = new DefaultComboBoxModel<>();
        for (String itemRoles : roles) {
            modelRoles.addElement(itemRoles);
        }
        
        if(Mode.equals("UPD") || Mode.equals("DLT")){
            usuario = (Usuario) dao.getById(id);
            modelRoles.setSelectedItem(usuario.getRol());
            txt_field_Usuario.setText(usuario.getUsername());
        }
        
        txt_field_Rol.setModel(modelRoles);
        
        if(Mode.equals("INS")){
            btn_operacion.setText("Insertar");
        }else if(Mode.equals("UPD")){
            btn_operacion.setText("Modificar");
        }else if(Mode.equals("DLT")){
            btn_operacion.setText("Borrar");
        }
        
    }
    
    private boolean validar(){
        if(txt_field_Rol.getSelectedItem().equals(null)){
            JOptionPane.showMessageDialog(parent, "Debe ingresar un rol.", "ERROR DE VALIDACIÓN", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try {
            String rol = txt_field_Rol.getSelectedItem().toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(parent, "Debe ingresar un valor válido para el rol.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(txt_field_Usuario.getText().equals(null) || txt_field_Usuario.getText().equals("")){
            JOptionPane.showMessageDialog(parent, "Debe ingresar un nombre de usuario.", "ERROR DE VALIDACIÓN", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(Mode.equals("INS")){
            if(txt_field_Clave.getPassword().equals(null) || txt_field_Clave.getPassword().length <= 0){
                JOptionPane.showMessageDialog(parent, "Debe ingresar una clave.", "ERROR DE VALIDACIÓN", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Background = new javax.swing.JPanel();
        label_Usuario = new javax.swing.JLabel();
        txt_field_Usuario = new javax.swing.JTextField();
        label_Password = new javax.swing.JLabel();
        txt_field_Clave = new javax.swing.JPasswordField();
        label_Rol = new javax.swing.JLabel();
        txt_field_Rol = new javax.swing.JComboBox<>();
        btn_operacion = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Usuarios");
        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(400, 350));
        setMinimumSize(new java.awt.Dimension(400, 350));
        setName("FormularioUsuarios"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 350));
        setSize(new java.awt.Dimension(700, 450));

        panel_Background.setBackground(new java.awt.Color(204, 204, 255));
        panel_Background.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        panel_Background.setLayout(new java.awt.GridLayout(6, 2, 40, 40));

        label_Usuario.setText("Nombre de usuario:");
        label_Usuario.setName("label_Usuario"); // NOI18N
        panel_Background.add(label_Usuario);

        txt_field_Usuario.setName("txt_field_Usuario"); // NOI18N
        panel_Background.add(txt_field_Usuario);

        label_Password.setText("Contraseña:");
        label_Password.setName("label_Password"); // NOI18N
        panel_Background.add(label_Password);
        panel_Background.add(txt_field_Clave);

        label_Rol.setText("Rol:");
        label_Rol.setName("label_Rol"); // NOI18N
        panel_Background.add(label_Rol);

        txt_field_Rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "recepcionista", "admin" }));
        txt_field_Rol.setName("txt_field_Rol"); // NOI18N
        panel_Background.add(txt_field_Rol);

        btn_operacion.setText("Operacion");
        btn_operacion.setName("btn_operacion"); // NOI18N
        btn_operacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_operacionActionPerformed(evt);
            }
        });
        panel_Background.add(btn_operacion);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.setName("btn_cancelar"); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        panel_Background.add(btn_cancelar);

        getContentPane().add(panel_Background, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_operacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operacionActionPerformed

        String txt_field_Clave_Hash = "";
        try {
            if(txt_field_Clave.getPassword().length > 0)
            {
                // Obtener la instancia del algoritmo MD5
                MessageDigest md = MessageDigest.getInstance("MD5");

                // Obtener el hash en forma de bytes
                byte[] passwordHashBytes = md.digest((new String(txt_field_Clave.getPassword())).getBytes());

                // Convertir el hash a una representación hexadecimal
                StringBuilder passwordHexString = new StringBuilder();
                for (byte b : passwordHashBytes) {
                    // Convertir cada byte a un valor hexadecimal
                    passwordHexString.append(String.format("%02x", b));
                }

                txt_field_Clave_Hash = passwordHexString.toString();   
            }
        } catch (NoSuchAlgorithmException ex) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        if(Mode.equals("INS")){
            boolean validacion = validar();
            if(validacion){
                
                Usuario newUsuario = new Usuario();
                newUsuario.setUsername(txt_field_Usuario.getText());
                newUsuario.setPasswordHash(txt_field_Clave_Hash);
                newUsuario.setRol(txt_field_Rol.getSelectedItem().toString());
                
                boolean operacion = dao.insert(newUsuario);
                if(operacion){
                    parent.refrescarDatos();
                    this.dispose();
                }
            }
        }
        if(Mode.equals("UPD")){
            boolean validacion = validar();
            if(validacion){
                usuario.setUsername(txt_field_Usuario.getText());
                usuario.setPasswordHash(txt_field_Clave_Hash);
                usuario.setRol(txt_field_Rol.getSelectedItem().toString());
                
                boolean operacion = dao.update(usuario);
                if(operacion){
                    parent.refrescarDatos();
                    this.dispose();
                }
            }
        }
        if(Mode.equals("DLT")){
            boolean operacion = false;
            try {
                operacion = dao.delete(usuario.getId());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(parent, "Ha ocurrido un error: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            if(operacion){
                parent.refrescarDatos();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(parent, "No fue posible eliminar el objeto seleccionado", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_operacionActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioUsuarios dialog = new FormularioUsuarios(new ListadoUsuarios(), true, Mode, id);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_operacion;
    private javax.swing.JLabel label_Password;
    private javax.swing.JLabel label_Rol;
    private javax.swing.JLabel label_Usuario;
    private javax.swing.JPanel panel_Background;
    private javax.swing.JPasswordField txt_field_Clave;
    private javax.swing.JComboBox<String> txt_field_Rol;
    private javax.swing.JTextField txt_field_Usuario;
    // End of variables declaration//GEN-END:variables
}
