/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UsuarioDAO;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author User
 */
public class JFrameLogin extends javax.swing.JFrame {
    
    private UsuarioDAO usuario_dao = new UsuarioDAO();
    
    /**
     * Creates new form JFrameLogin
     */
    public JFrameLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        btn_Titulo = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        usuarioTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        claveTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(300, 300));
        setName("frame_Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 300));

        loginPanel.setBackground(new java.awt.Color(204, 204, 255));
        loginPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        loginPanel.setToolTipText("Login Panel");
        loginPanel.setName("loginPanel"); // NOI18N
        loginPanel.setLayout(new java.awt.GridLayout(6, 1, 10, 10));

        btn_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/review.png"))); // NOI18N
        btn_Titulo.setText(" Sistema de reservas");
        btn_Titulo.setMaximumSize(new java.awt.Dimension(70, 120));
        btn_Titulo.setMinimumSize(new java.awt.Dimension(70, 120));
        btn_Titulo.setPreferredSize(new java.awt.Dimension(70, 120));
        loginPanel.add(btn_Titulo);

        userLabel.setText("Usuario:");
        userLabel.setName("userLabel"); // NOI18N
        loginPanel.add(userLabel);

        usuarioTextField.setName("usuarioTextField"); // NOI18N
        loginPanel.add(usuarioTextField);

        passwordLabel.setText("Contraseña:");
        passwordLabel.setName("passwordLabel"); // NOI18N
        loginPanel.add(passwordLabel);

        claveTextField.setToolTipText("");
        claveTextField.setName("claveTextField"); // NOI18N
        loginPanel.add(claveTextField);

        loginButton.setText("Iniciar sesión");
        loginButton.setName("loginButton"); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton);

        getContentPane().add(loginPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // Se declara una variable para almacenar el hash de la contraseña en formato hexadecimal
        String claveTextFieldHash = "";

        try {
            // Obtener la instancia del algoritmo de hash MD5
            MessageDigest md = MessageDigest.getInstance("MD5");

            // Convertir la contraseña ingresada en el TextField a un array de bytes
            // La contraseña se obtiene con getPassword() y se convierte a un String antes de obtener sus bytes
            byte[] passwordHashBytes = md.digest((new String(claveTextField.getPassword())).getBytes());

            // Crear un StringBuilder para construir la representación hexadecimal del hash
            StringBuilder passwordHexString = new StringBuilder();

            // Iterar sobre los bytes generados del hash de la contraseña
            for (byte b : passwordHashBytes) {
                // Convertir cada byte a su representación hexadecimal de 2 dígitos y agregar al StringBuilder
                passwordHexString.append(String.format("%02x", b));
            }

            // Asignar el valor hexadecimal final a la variable claveTextFieldHash
            claveTextFieldHash = passwordHexString.toString();
        } catch (NoSuchAlgorithmException ex) {
            // Si ocurre un error al obtener el algoritmo MD5, mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        // Si no se encontró un usuario válido, mostrar un mensaje de error
        if(!this.usuario_dao.validateCredentials(this.usuarioTextField.getText(), claveTextFieldHash)) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            // Obtener el usuario conectado
            Usuario usuario_conectado = (Usuario)this.usuario_dao.getByUserName(this.usuarioTextField.getText());
            
            // Iniciar programa
            ListadoMenu frame_Menu = new ListadoMenu(usuario_conectado);
            frame_Menu.setLocationRelativeTo(null);
            frame_Menu.setVisible(true);
            
            // Si se encontró un usuario válido, cerrar la ventana actual
            this.dispose();
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameLogin frame_Login = new JFrameLogin();
                frame_Login.setLocationRelativeTo(null);
                frame_Login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Titulo;
    private javax.swing.JPasswordField claveTextField;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables
}
