/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Usuario;

/**
 *
 * @author User
 */
public class ListadoMenu extends javax.swing.JFrame {

    Usuario usuario_conectado = null;
    ListadoHabitaciones frame_Habitaciones = new ListadoHabitaciones();
    ListadoHuespedes frame_Huespedes = new ListadoHuespedes();
    ListadoPagos frame_Pagos = new ListadoPagos();
    ListadoReservas frame_Reservas = new ListadoReservas();
    ListadoUsuarios frame_Usuarios = new ListadoUsuarios();

    /**
     * Creates new form ListadoMenu
     */
    public ListadoMenu() {
        initComponents();
        btn_Habitaciones.setEnabled(false);
        btn_Huespedes.setEnabled(false);
        btn_Pagos.setEnabled(false);
        btn_Reservas.setEnabled(false);
        btn_Usuarios.setEnabled(false);
    }
    
    /**
     * Creates new form ListadoMenu
     */
    public ListadoMenu(Usuario usuario_conectado) {
        initComponents();
        this.usuario_conectado = usuario_conectado;
        
        if(this.usuario_conectado != null && "admin".equals(this.usuario_conectado.getRol()))
        {
            btn_Usuarios.setEnabled(true);
        }
        else
        {
            btn_Usuarios.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Menu = new javax.swing.JPanel();
        btn_Habitaciones = new javax.swing.JButton();
        btn_Huespedes = new javax.swing.JButton();
        btn_Pagos = new javax.swing.JButton();
        btn_Reservas = new javax.swing.JButton();
        btn_Usuarios = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Módulos disponibles");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(600, 300));
        setName("frame_Listado_Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 300));

        panel_Menu.setBackground(new java.awt.Color(204, 204, 255));
        panel_Menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panel_Menu.setMinimumSize(new java.awt.Dimension(540, 200));
        panel_Menu.setPreferredSize(new java.awt.Dimension(540, 200));
        panel_Menu.setLayout(new java.awt.GridLayout(2, 3, 10, 10));

        btn_Habitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bedroom.png"))); // NOI18N
        btn_Habitaciones.setText("Habitaciones");
        btn_Habitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HabitacionesActionPerformed(evt);
            }
        });
        panel_Menu.add(btn_Habitaciones);

        btn_Huespedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/client.png"))); // NOI18N
        btn_Huespedes.setText("Huéspedes");
        btn_Huespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuespedesActionPerformed(evt);
            }
        });
        panel_Menu.add(btn_Huespedes);

        btn_Pagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cash-payment.png"))); // NOI18N
        btn_Pagos.setText("Pagos");
        btn_Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PagosActionPerformed(evt);
            }
        });
        panel_Menu.add(btn_Pagos);

        btn_Reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/booking.png"))); // NOI18N
        btn_Reservas.setText("Reservas");
        btn_Reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReservasActionPerformed(evt);
            }
        });
        panel_Menu.add(btn_Reservas);

        btn_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/woman.png"))); // NOI18N
        btn_Usuarios.setText("Usuarios");
        btn_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UsuariosActionPerformed(evt);
            }
        });
        panel_Menu.add(btn_Usuarios);

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        panel_Menu.add(btn_Salir);

        getContentPane().add(panel_Menu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HabitacionesActionPerformed
        this.frame_Habitaciones.setLocationRelativeTo(null);
        this.frame_Habitaciones.setVisible(true);
    }//GEN-LAST:event_btn_HabitacionesActionPerformed

    private void btn_HuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuespedesActionPerformed
        this.frame_Huespedes.setLocationRelativeTo(null);
        this.frame_Huespedes.setVisible(true);
    }//GEN-LAST:event_btn_HuespedesActionPerformed

    private void btn_PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PagosActionPerformed
        this.frame_Pagos.setLocationRelativeTo(null);
        this.frame_Pagos.setVisible(true);
    }//GEN-LAST:event_btn_PagosActionPerformed

    private void btn_ReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReservasActionPerformed
        this.frame_Reservas.setLocationRelativeTo(null);
        this.frame_Reservas.setVisible(true);
    }//GEN-LAST:event_btn_ReservasActionPerformed

    private void btn_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UsuariosActionPerformed
        this.frame_Usuarios.setLocationRelativeTo(null);
        this.frame_Usuarios.setVisible(true);
    }//GEN-LAST:event_btn_UsuariosActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        this.frame_Habitaciones.dispose();
        this.frame_Huespedes.dispose();
        this.frame_Pagos.dispose();
        this.frame_Reservas.dispose();
        this.frame_Usuarios.dispose();
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Habitaciones;
    private javax.swing.JButton btn_Huespedes;
    private javax.swing.JButton btn_Pagos;
    private javax.swing.JButton btn_Reservas;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_Usuarios;
    private javax.swing.JPanel panel_Menu;
    // End of variables declaration//GEN-END:variables
}
